### ISSUE TITLE
Connected But Won't Authorize 0.9.0-RC3

### ISSUE THREAD

**Issue by BradRuderman** [paralect/robomongo#1010]
I am trying to connect but can't authorize when connecting to a replicaSet. I am using the OS X 0.9.0 RC-3. The connection string didn't copy over from the older version 0.8.5 however when recreating the connection string (including auth db and credentials), and click test I see the following. I am confident its not an auth issue with the username/password.
<img width="730" alt="diagnostic_and_connection_settings_and_mongodb_connections_and_robomongo_0_9_0-rc3" src="https://cloud.githubusercontent.com/assets/2366784/12694623/413a958a-c6e8-11e5-8240-0f71dde800e9.png">

**Comment by anorsich** [comment]
@BradRuderman In version 0.9.0 connections via ssh/ssl [were disabled](http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/). Also, because of this change we now store Robomongo settings in another folder. Your old config is safe and stored at `~/.config/robomongo/`, while new config stored at `~/.config/robomongo/0.9/`. If you have many connections it might make sense to copy old connection strings over to the new location: `cp ~/.config/robomongo/robomongo.json ~/.config/robomongo/0.9/robomongo.json`. Also, that could help double check human error (invalid username or password or auth db).

If that still won't work, could you post your mongodb instance configuration here (including configuration of authentication) - that should help us reproduce the issue. We tested 0.9 release against many different databases (2.6, 3.0, 3.2) with and without auth, local and remote. 

We are here to help.

**Comment by BradRuderman** [comment]
I copied the file and still having the issue. Here is the best to describe my configuration:

1) Mongo 2.6.1/2.6.4 (Tested on both versions, having issues)
2) Using default MONGODB-CR auth
3) Replica Set (I am trying to connect to the master)

Here is a sample connection json that worked on 0.8.5, but not in 0.9.0 rc3. I changed sensitive info.

```
  {
   "connectionName" : "Production Read Only",
   "credentials" : [
    {
     "databaseName" : "admin",
     "enabled" : true,
     "userName" : "adminUser",
     "userPassword" : "password"
    }
   ],
   "defaultDatabase" : "test",
   "serverHost" : "local.test.com",
   "serverPort" : 27017,
   "sshAuthMethod" : 0,
   "sshHost" : "",
   "sshPassphrase" : "",
   "sshPort" : 22,
   "sshPrivateKey" : "",
   "sshPublicKey" : "",
   "sshUserName" : "",
   "sshUserPassword" : "",
   "sslEnabled" : false,
   "sslPemKeyFile" : ""
  },
```

**Comment by anorsich** [comment]
@BradRuderman Ohh, I see. The issue is replica set (#116)

**Comment by BradRuderman** [comment]
@anorsich I know there is a feature request to support ReplicaSet, however in 0.8.5, at least I could connect to the master without difficulty. Now I can't even connect to the master. This has made 0.9.0 rc-3 completely unusable for anyone with a replicaset, versus just not supporting the replica set functionality.

**Comment by vietzon** [comment]
Same problem here. I just download the RC and could not connect to the master. Older version was OK

**Comment by schetnikovich** [comment]
@BradRuderman @vietzon We are planning to address Replica Sets in next RC release. Together with restored logging, this is our current priority.

**Comment by BradRuderman** [comment]
@schetnikovich @anorsich  All respect (full disclosure I donated, and shared the link out) if the campaign fails, will rc3 be the last RC? Is it possible to patch this to keep it usable for the given community?

**Comment by anorsich** [comment]
@BradRuderman RC3 won't be the last release for sure, we want still to do some more improvements, but if won't reach out target that would be much harder to support Robomongo without dedicated developer. P.S. We just released new version of the [Robomongo](http://blog.robomongo.org/robomongo-rc4/) which supports connections to the replica sets (including slaves) and mongodb-cr/scram-sha-1 authentication. Let us know if it work for you.

**Comment by anorsich** [comment]
@BradRuderman Feel free to reopen this ticket if you'll find any issues.
