### ISSUE TITLE
incorrect int values

### ISSUE THREAD

**Issue by fajnalowiec** [paralect/robomongo#1022]
So, I have 64-bit windows and 0.8.5 version of Robomongo (it seems to be 32-bit).
There is although incorrect integer values handling there.
So here you can see the document I've added with e.g.: firstSeenDate as 1450367379:
`http://imgur.com/GCJL1SX`
And whenever I change the view, want to view/ edit it then the values are changed and it looks like this:
`http://imgur.com/wpIcgnp`

**Comment by anorsich** [comment]
@fajnalowiec Thank you for reporting this issue! It is known issue fixed in [0.9.0 RC-3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/), but 0.9.0 RC-* series does not have 32 bit version. If you have 64 bit pc or laptop you might consider upgrading to latest version of Robomongo.

You could also watch ticket #1009 to see development progress of 32 bit os support.

**Comment by anorsich** [comment]
@fajnalowiec Since this issue was fixed in latest releases, I am going to close this ticket. If it still does not work for you - feel free to reopen!
