### ISSUE TITLE
User Assertion: 18:auth failed

### ISSUE THREAD

**Issue by brkattk** [paralect/robomongo#1025]
I'm getting this error when trying to connect:

`2016-02-09T18:57:00.670-0500 D -        [thread2] User Assertion: 18:auth failed`

I'm using version 0.9.0 on OS X and trying to connect to mongo version 3.0.9 on Mongolab.

Using `MONGODB-CR` auth mechanism and the proper credentials/db/host

**Comment by anorsich** [comment]
@brkattk Thank for reporting this issue! I know for sure that only 3.0 have`MONGODB-CR` authentication only in case if your database was upgraded from 2.6, otherwise, it will have `SCRAM-SHA-1` authentication. Could you try `SCRAM-SHA-1` to just exclude a case, that you use invalid authentication when trying to connect. If that won't help we will try to reproduce and fix that issue.

**Comment by brkattk** [comment]
@anorsich Thank you! I could've sworn I tried that authentication, but I suppose I didn't because it worked. Thanks again!

**Comment by blainsmith** [comment]
This also worked for me too. @brkattk and I are connecting to the same Mongo instance. :+1:

**Comment by anorsich** [comment]
@brkattk @blainsmith Happy to hear that it worked for you and that this is not a Robomongo bug :) Closing this ticket.
