### ISSUE TITLE
Robomongo 0.9.0-RC5 connectivity issue for mongodb 2.6.8 version

### ISSUE THREAD

**Issue by vakkalagadda** [paralect/robomongo#1036]
Hi Paralect/Robomongo Team,

We're using mongodb 2.6.8 version and we use robomongo 0.8.5 version for connecting to the mongo DB. It absolutely work with no issues..

But we see the connectivity issue to 2.6.8 mongodb version with the Robomongo 0.9.0-RC5 (Error pop up with message 'Cannot connect to MongoDB (host:port), error :  Unable to connect to MongoDB').  Even the authorization is failing when we click on the Test button to check the connection.

The only difference we see in the robomongo connection creation part is, In the 0.8.5 version, we have the SSL tab where we check the Use SSL Protocol check box. In the 0.9.0-RC5, I have the issue for both the Auth Mechanism listed in the drop down in Authentication tab.

Appreciate for all the support. I look forward for your response. 

Thanks
Anil Kumar

**Comment by myaskevich** [comment]
#1002

**Comment by myaskevich** [comment]
Hi,
This is probably because your connection requires SSL support.
As you probably might have noticed the [current release limitations announced in our blog a while back](http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/), we have decided to rework SSL/SSH support and therefore disabled it for a moment..
Please use https://github.com/paralect/robomongo/issues/1002 to track the progress on it.
Sorry for inconvenience.
Best regards,
Max
Robomongo Team

**Comment by vakkalagadda** [comment]
Thanks for your update Max. Do we've any date when we can expect it in the latest robomongo version?

**Comment by anorsich** [comment]
@vakkalagadda 
Just wanted to share some great news with you! We've release RC8 just a week ago and it now supports SSH tunnels. SSL is our next priority and we are working on it right now. You can read some more details about our roadmap for the next few months in our [blog post](http://blog.robomongo.org/robomongo-rc8/). I am also going close this issue, let's use #1002 to track our progress.
