### ISSUE TITLE
Delete Document Key Shortcut only works with multi selections

### ISSUE THREAD

**Issue by synthomat** [paralect/robomongo#1039]
After selecting one row in the BSON view and hitting Del-Key (fn+backspace on mac), nothing happens. Deleting documents only works with multi selections.

**Comment by schetnikovich** [comment]
@synthomat, thank you for PR! We decided to not delete existed `onDeleteDocument()` in order to minimise possible regression. You can check what we made in [this commit](https://github.com/paralect/robomongo/commit/7dfd9184b7a19e278fcafef64f31abafb0e47453). 

We also added support for more familiar Mac OS X shortcut: `Command + Delete`.

This fix will be part of the next build, but you can pull changes and use it today. Thank you for the help!

**Comment by schetnikovich** [comment]
Actually, when we picked changes from your [PR](https://github.com/paralect/robomongo/pull/1037), in particular support for shortcuts for recursive expand, we utilised your switch statement. Thank you!
