### ISSUE TITLE
Can't build on debian jessie (anymore)

### ISSUE THREAD

**Issue by miclill** [paralect/robomongo#1048]
Because of cmake version 3.0.2

Is there a good reason robomongo needs cmake version >3.1 now?

Regards

**Comment by schetnikovich** [comment]
@miclill We added support for CMake 3.0. I had a chance to test it only on Mac OS X for now. Could you please check how it works for Linux?

There is no good reason for Robomongo to request CMake version 3.1.

**Comment by miclill** [comment]
I'm getting this now (with mongodb-dev installed):
`-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could not find Robomongo Shell (MongoDB fork).  Make sure that
  CMAKE_PREFIX_PATH points to Robomongo Shell project root.

   (missing:  MongoDB_DIR) 
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMongoDB.cmake:104 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)
`

**Comment by schetnikovich** [comment]
Robomongo is based on modified version of MongoDB, that we call [Robomongo Shell](https://github.com/paralect/robomongo-shell). It means that you cannot use `mongodb-dev` package on Debian. 

Error also states, that you should specify `CMAKE_PREFIX_PATH` to the location of Robomongo Shell and Qt 5:

```
cd /some/build/dir
cmake -D "CMAKE_PREFIX_PATH=/path/to/qt-5.5/5.5/clang_64;/path/to/robomongo-shell" /path/to/robomongo
```

We use very simple [bash scripts](https://github.com/paralect/robomongo/tree/master/bin) for all building tasks that you can read in order to understand how we execute CMake. Refer to the [documentation](https://github.com/paralect/robomongo/blob/master/docs/BuildingRobomongo.md) to get an overview of these scripts.

Let's work together to build Robomongo on Debian. Waiting for farther feedback.

**Comment by miclill** [comment]
Hmm. I don't really understand. 0.8.5 built just fine against mongodb-dev.
Would I also need to use this modified version of mongo? Then this wouldn't make sense to me since I use robomongo with a remote mongo database which I'm not in charge of.

**Comment by myaskevich** [comment]
Hi @miclill 
Yes, you need to use our mongo shell fork in order to build version 0.8.5 as well, even though the original mongo worked for you.
Should you have any other questions on this topic, please let us know.
Once you figure it out, please consider closing this issue.
Thank you!

**Comment by schetnikovich** [comment]
Version 0.8.5 also doesn't use `mongodb-dev`. It uses modified version of MongoDB 2.4 that is a part of the sources. Starting from 0.9.0 we moved MongoDB sources to [separate repository] (https://github.com/paralect/robomongo-shell) (Robomongo Shell) and now it is required to build Robomongo Shell separately. 

Back to your questions:

> Would I also need to use this modified version of mongo?

Yes, if you are building 0.9.0 version. No, if you are building 0.8.5. We do not recommend to use version 0.8.5, because it has several critical issues that are now fixed. For instance, bug with floating point numbers, that was [described in our blog post](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/).

> Then this wouldn't make sense to me since I use robomongo with a remote mongo database which I'm not in charge of.

Single version of Robomongo supports several versions of MongoDB. Here is a support matrix for Robomongo:

<table>
  <tr>
    <td>MongoDB version</td>
    <td>Robomongo 0.8.5</td>
    <td>Robomongo 0.9.0</td>
  </tr>
  <tr>
    <td>2.4</td>
    <td><b>Yes</b></td>
    <td>No</td>
  </tr>
  <tr>
    <td>2.6</td>
    <td><b>Yes</b></td>
    <td><b>Yes</b></td>
  </tr>
  <tr>
    <td>3.0</td>
    <td>No</td>
    <td><b>Yes</b></td>
  </tr>
  <tr>
    <td>3.2</td>
    <td>No</td>
    <td><b>Yes</b></td>
  </tr>
</table>

It means, that if you'll compile 0.9.0 version of Robomongo, it will support MongoDB 2.6 - 3.2.

Let us know if you have more questions.

**Comment by miclill** [comment]
Thank you for the detailed explanation. I can understand better now.

**Comment by schetnikovich** [comment]
@miclill You are welcome!
