### ISSUE TITLE
No more x86 32 bit releases? :-)

### ISSUE THREAD

**Issue by acrolink** [paralect/robomongo#1066]
I hope you continue providing a 32 but version of upcoming releases.

**Comment by anorsich** [comment]
Hi @mirchow,
Starting from MongoDb 3.0 The MongoDB company [won't support](https://docs.mongodb.org/manual/faq/fundamentals/#what-are-the-limitations-of-32-bit-versions-of-mongodb) 32 bit versions. Since Robomongo integrates MongoDB shell we might not be able to support 32 bit binaries as well. We are still planning to try to build 32 bit binaries but do not have any ETA on implementing this yet. 

We already have a ticket for 32 bit releases #1009. Let use it to track implementation progress. Going to close this one as a duplicate.
