### ISSUE TITLE
Complex queries crashing on 0.9.0-RC7 with mongodb 2.6.11

### ISSUE THREAD

**Issue by darkdigitaldream** [paralect/robomongo#1067]
Mac OS/X:

$and{} clauses placed within an $or{} clause are causing a stack overflow when interacting with mongodb 2.6.11.
eg:
db.getCollection('mycollection').find({$or: [{$and: [{a: true}, {b: true}]}, {c: true}]})

results in
InternalError: too much recursion

problem not reproducible using mongodb 2.6.6 or robomongo 8.5

a second call to the query within the same tab returns proper results.

**Comment by anorsich** [comment]
@darkdigitaldream It looks like the issue is not with Robomongo, but with MongoDB shell. Robomongo internally uses MongoDB shell, version 3.2. I can't find an exactly same bug on MongoDB Jira, but there are [few similar](https://jira.mongodb.org/browse/SERVER-13952?jql=text%20~%20%22too%20much%20recursion%22). I think the best way to get it fixed is to post a bug on MongoDB Jira. Shell errors are out of the scope of Robomongo project, at least at the moment. 

Robomongo 8.5 used an older version of the shell (2.4), it looks this bug was introduced in the most recent version of the shell.

**Comment by anorsich** [comment]
@darkdigitaldream  Closing this one, feel free to reopen if needed!

**Comment by macdabby** [comment]
I'm running into this problem also.  Just as an FYI, simply adding a semicolon to the end seems to work sometimes
