### ISSUE TITLE
No such method: Robomongo::MongoServer::handle(DropDatabaseResponse*)

### ISSUE THREAD

**Issue by zladuric** [paralect/robomongo#1083]
Hi,

I've just ran robomongo locally (due to still setting up a new system).  0.9.0-RC7

I've seen this in the log:

```QMetaObject::invokeMethod: No such method Robomongo::MongoServer::handle(DropDatabaseResponse*)
Candidates are:
    handle(EstablishConnectionResponse*)
    handle(LoadDatabaseNamesResponse*)
    handle(InsertDocumentResponse*)
    handle(RemoveDocumentResponse*)```

The app didn't crash, everything behaved normally, but I'm not sure if it's relevant. And it looks remotely like related to what I've reported before: https://github.com/paralect/robomongo/issues/1070

Is it just debug info or is there really a handler missing?

I don't know if it's relevant, so I'll just leave it here for you guys to triage.

**Comment by schetnikovich** [comment]
@zladuric, this log message indicates, that we do not report completeness status of the "drop database" operation to user. Not very critical problem, but still important and needs to be fixed. We improved error reporting in RC8 dramatically, but seems that this case was omitted. 

Thank you for report! Will be fixed in the upcoming RC9.

**Comment by schetnikovich** [comment]
@zladuric Fixed and will be available in RC9. Thanks again!
