### ISSUE TITLE
font problem in text view (Ubuntu 12.04)

### ISSUE THREAD

**Issue by Thomas-Lebeau** [paralect/robomongo#423]
Well, I think this screenshot is self explaining.
I'm on ubuntu 12.04
![robomongo 0 8 4 rc2_001](https://f.cloud.github.com/assets/1926949/1550386/812f0e16-4e02-11e3-8406-4408a239114c.png)

**Comment by stennie** [comment]
For linux, the font being used in Robomongo 0.8.x is [`Monospace`](https://github.com/paralect/robomongo/blob/master/src/robomongo/gui/GuiRegistry.cpp#L298).

I can't reproduce this issue in Ubuntu 14.04 (and it's rather old now) so please create a new issue with updated details if you are still seeing problems.

I think a better fix will be #645 (add preference to change font in UI, rather than hardcoding).

**Comment by Voronenko** [comment]
Agree, #645 would be the best solution
