### ISSUE TITLE
Escaping of backslash in collection names

### ISSUE THREAD

**Issue by makebytes** [paralect/robomongo#510]
Collection names with backslash are not escaped on double click (View documents).
This causes confusion because Mongo threats it as correct collection name but returns no documents.

Example:
Collection name: ABC\123
Generated find query: db['ABC\123'].find() (which always returns no documents)
Proper find query: db['ABC\\123').find()

**Comment by lazareveugene** [comment]
i have another case in our db we have collection with name auth, so double click also not working because robomongo produce this statement db.auth.find().
this statement return error 
TypeError: db.auth.find is not a function (shell):1
because auth is also name of function auth()
if robomongo will construct statement like this: db['auth'].find()
it will be ok

we use spring-data-mongodb and this orm properly handle such cases

**Comment by stennie** [comment]
@lazareveugene This has been fixed in Robomongo 0.8.5 (for #414). Instead of trying to special case reserved collection names (which vary by version of MongoDB) the alternate syntax is now used for double click, eg:
```
db.getCollection('auth').find({})
```

**Comment by lazareveugene** [comment]
cool

i will update my version
