### ISSUE TITLE
Way to change the height of the command window

### ISSUE THREAD

**Issue by ardan-bkennedy** [paralect/robomongo#646]
It would be really helpful to be allowed to change the height of the command window. Sometimes I want to see more of the code I am running and less of a view.

**Comment by Jargonius** [comment]
This and #657 are duplicates.

**Comment by viztastic** [comment]
+1

**Comment by simsekgokhan** [comment]
Hi guys, thanks a lot for your interest, sorry for the long delay. We have finished development of a new feature which will give you full screen query editor and dock-able output window (for each tab). 

Please see the screenshots here:
[New Feature: Full Screen Query Editor (Dockable Output Window)](1187) 

Feature is under internal testing, planing to release next week. 
Follow the latest releases and news here: 
https://twitter.com/Robomongo

**Comment by juliashibalko** [comment]
I'm closing this card as implemented and fixed in 0.9.0 release (https://github.com/paralect/robomongo/issues/1187).
Please see the new Robomongo 0.9.0 with new features described here http://blog.robomongo.org/robomongo-0-9-0-final/
Download site: https://robomongo.org/download

In any case please feel free to create new ticket. Thank you!
Follow us for latest news: https://twitter.com/Robomongo
