### ISSUE TITLE
Document edit window sizing

### ISSUE THREAD

**Issue by XAMeLi** [paralect/robomongo#736]
Setup:
On a Windows 7 system with two HD displays (1920x1080), the main display is in portrait mode (effectively, 1080x1920 resolution).

Steps to reproduce:
1. Open Robomongo on secondary display (1920x1080).
2. Search for documents.
3. Edit one of the documents.

Observed behavior:
Edit window opens on secondary display with a height of about 1800 pixels. The top and bottom of the window are not visible.
The only way to move the window is by using Alt+Space and arrow keys.
Even after the title of the window is visible, it seems like it has MinHeight set and there's no way to make the window smaller.
This behavior not observed when both screens are defined in landscape mode.

Expected behavior:
Edit window has MinHeight/MinWidth that is not dependent on screen configuration, and are less than 1000 pixels.

**Comment by pgifford** [comment]
This is not just a Windows issue. Oddly enough I have the exact same monitor configuration except I'm using RHEL 6.5 (Gnome 2.28.2) and have encountered this issue as well. 

It appears that the edit/view window gets its geometry from the primary display even if Robomongo is maximized in the secondary display. The edit/view window opens in the same display as Robomongo, hence the problem.

My workaround is to press ESC to close the edit/view window, then move Robomongo to the primary display and re-open the view/edit window.  The expected behavior is that the view/edit window will have dimensions and position within the bounds of the display in which it is opened.

**Comment by justintaylor** [comment]
I've seen this too.

**Comment by stennie** [comment]
@XAMeLi @pgifford @justintaylor Can you retest with the [0.8.5 release previews](https://github.com/paralect/robomongo/issues?q=milestone%3A%22Robomongo+0.8.5%22+%22create+0.8.5%22+label%3Atask)? There have been code changes as well as updates to a newer version of Qt (5.3.2).

Thanks!

**Comment by justintaylor** [comment]
@stennie Looks good! (Win 8.1)

**Comment by stennie** [comment]
@justintaylor Thanks for confirming!
