### ISSUE TITLE
Does not work with mongodb 3.0

### ISSUE THREAD

**Issue by sherry-ummen** [paralect/robomongo#751]

**Comment by antmanler** [comment]
+1

**Comment by stennie** [comment]
This is being addressed as part of #520.

FYI, Robomongo still works with MongoDB 3.0 unless you are using features like the new WiredTiger storage engine or new authentication. Definitely a hassle if you want to test out the 3.0 RCs.

I'm hoping to have an updated release available close to the timing of MongoDB 3.0 GA in March.

**Comment by sherry-ummen** [comment]
ok Thanks that's right with WiredTiger engine it does not work.

**Comment by luislobo** [comment]
Well, anything we can do to help? We're using MongoDB 3.0 with WiredTiger and its definitely not working.

**Comment by stennie** [comment]
@luislobo What sort of help are you offering? I've updated the [project README](https://github.com/paralect/robomongo) with more examples of how anyone might be able to contribute. You should definitely not expect Robomongo 0.8.x to work with either WiredTiger storage engine or the new SCRAM-SHA-1 auth in MongoDB 3.0.

WiredTiger / 3.0 compatibility is a major change, as it ties in with upgrading the embedded shell (from MongoDB 2.4 to 3.0), JavaScript engine (from SpiderMonkey to V8), and the various APIs that have changed (eg. the logger class which is used throughout Robomongo). The work here is already in progress but there are still some build issues to fix before getting others hacking at the integration.

The 3.0 shell update is the focus of the next Robomongo release (0.9.0), and will fix a swath of issues due to the aging JavaScript/shell version currently used. I've assigned issues that myself or someone else are working on, so you could also have a look at [unassigned issues](https://github.com/paralect/robomongo/issues?q=is%3Aopen+milestone%3A%22Robomongo+0.9.0%22++no%3Aassignee) tagged for the 0.9.0 release. I would consider most of the unassigned issues "nice to haves" (i.e. 3.0 support is the main required feature), but many are also smaller items that could be picked by other contributors while the main code changes are being done.

**Comment by 4lifedev** [comment]
Are there any updates on the work being done on 0.9.0?  Should we forget about this project and move on to something else or should we wait?

**Comment by ChALkeR** [comment]
#520, #707.

**Comment by laicosly** [comment]
+1

**Comment by snowdream** [comment]
+1

**Comment by thewaywest** [comment]
+1 -- but Robomongo is a great tool, would love to be able to use it with my new dev.

**Comment by sherry-ummen** [comment]
Just use Mongochef and forget about Robomongo as I have moved on.

**Comment by thewaywest** [comment]
Thanks: done.

**Comment by iici-yk** [comment]
+50

**Comment by syzer** [comment]
+!

**Comment by chmller** [comment]
You can query your Collections like so:
db.getCollection("dummycol_1").find()

![robomongo_0_8_5](https://cloud.githubusercontent.com/assets/5073599/11428860/af6930fc-9470-11e5-9630-fdedf2220d94.png)


Works for me with MongoDB 3.0.7 + Robomongo 0.8.5

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.

Thank you all for patience!

**Comment by brkattk** [comment]
I have Robomongo 0.9.0 on OS X and a Mongolab database that is version 3.0.9. I am unable to connect.
