### ISSUE TITLE
Pointers on working with at-rest encryption

### ISSUE THREAD

**Issue by swinton** [paralect/robomongo#763]
Hi there,

We're using MongoDB in the Healthcare space, and due to the need for [HIPAA](https://en.wikipedia.org/wiki/Health_Insurance_Portability_and_Accountability_Act) compliance, our data is encrypted at-rest.  I'm researching possible methods for querying the data securely, and one idea I'm exploring is forking robomongo to include on-the-fly decryption of the data, for querying purposes.

If successful, I'd love to be able to offer our work up for others, either through this official repo, or an alternative, so others in the space can also benefit from our work.

Could you provide some pointers of where I might start? What points in the application / core would need to be modified to support this? 

Much appreciated,
Steve

**Comment by stennie** [comment]
@swinton If your data is encrypted at rest, I don't think you want to head down the path of decrypting data in the client. In order for the MongoDB server to usefully query data (rather than opaque encrypted blobs), the decryption needs to happen at a filesystem or storage level on the server. 
Similarly, given the security and auditing requirements for HIPPA I don't think you would want to allow users to directly connect to your database. More appropriate interaction would likely be part of a custom administrative interface.

There are several partner solutions for transparent encryption of data at rest that will work with MongoDB, for example: Bitlocker, Vormetric, IBM Guardium. It's also worth noting that encryption at rest is not solely sufficient to cover HIPAA requirements. Encryption over the wire, auditing, user roles, redaction, and other security or data management provisions will likely be needed.

For more background see:
 * [Making HIPAA Compliant Applications with MongoDB](http://www.mongodb.com/blog/post/making-hipaa-compliant-applications-mongodb)
 * [FHIR: Spark.Net: Making MongoDB storage HIPAA compliant](http://stackoverflow.com/questions/25274848)
