### ISSUE TITLE
new release anytime soon?

### ISSUE THREAD

**Issue by tessus** [paralect/robomongo#767]
I was wondering, if there will be a new release (binary) soon. Even, if it is just a pre-release.

Version 0.8.4 does not really work with user and roles, if MongoDB >= 2.6.

**Comment by martinduparc** [comment]
Having the authors do it for each pre-release is time consuming. It is fairly simple to create a build if you follow these directions https://github.com/paralect/robomongo/wiki/Build-Robomongo

If you do create a build, feel free to share it with the community

**Comment by tessus** [comment]
@martinduparc the last binary release was over a year ago.

Also, the developers already have all the pre-reqs on their machines. I don't. So it is fairly easy to just zip their compiled app from the Xcode output dir and attach it.
They have to compile it anyway to test the stuff. So the only annoyance for them is to zip and upload it.

**Comment by martinduparc** [comment]
Don't get me wrong, I would love a binary (0.8.5 has so many improvements) but there usually are extra steps you need to take when going from a debug build to a production one (possible certificates, icons, ...).

**Comment by tessus** [comment]
no, a debug app is entirely standalone. it runs. I don't care, if it is signed or not. we are talking about a pre-release here. not a final release, which I might grant you, would take 5 minutes more to do.

**Comment by stennie** [comment]
@tessus This an open source project driven by volunteer efforts. More volunteers would definitely help things move faster (in general, but particularly in the area of packaging & testing).

I've been trying to push things along in my spare time since the project went quiet last year, but that's been split between:
 - finish packaging the 0.8.5 release (there are improvements, to be sure)
 - finish integrating an updated shell for the 0.9.0 release (which imho is much more important for usability / future of Robomongo)
 - work/family/life commitments (there are only so many weekends I can spare)

The main impediments to getting new binary releases out are:
 - time for properly packaging and testing: release packages need to work on a computer without the Qt development libraries installed and work with recent flavours of Windows/OS X/etc
 - there are some platform-specific build errors to resolve
 - I haven't packaged the Linux / Windows releases before
 - My main dev environment is OS X and I find it very time consuming to get my Linux/Windows VMs set up with the right build tools (and then have clean VMs to test releases)

> I was wondering, if there will be a new release (binary) soon. Even, if it is just a pre-release.

There will be a 0.8.5 soon (for OS X, at least). I've asked some folks for help on the Linux/Windows builds (including Paralect, the nominal project owners) as it would be nice to have updated releases for all platforms.

> Version 0.8.4 does not really work with user and roles, if MongoDB >= 2.6.

Unfortunately, version 0.8.5 also won't address that issue. These fixes are targeted for a [0.9.0 release milestone](https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0).

> no, a debug app is entirely standalone. it runs. I don't care, if it is signed or not. 

You can build a debug or release app from source. The releases aren't signed, either, at the moment. I believe the process is far less trivial than you suggest, but perhaps should err on the side of pushing out Something and let others work out how to support that.

> we are talking about a pre-release here. not a final release, which I might grant you, would take 5 minutes more to do.

It definitely takes more than 5 minutes to make a release .. or we wouldn't be having this conversation :)

**Comment by tessus** [comment]
@stennie Thank you for your detailed answer.

Regarding a binary release, I think you misunderstood my thinking: you tagged https://github.com/paralect/robomongo/commit/4738ad7f564f6c4e61b41f86d2fd376c01f52833 as a pre-release on Jan 4th. Thus I thought you clicked the compile button in Xcode (or used the command line), because you had to test this commit point.
Therefore there should be a binary Debug version of this commit point somewhere on your hard disk (e.g. `<home>/Library/Developer/Xcode/DerivedData/Build/Products/Debug`).
Zipping this binary and attaching it to the tag should be fairly easy and should take less than 5 minutes.

Please don't take this the wrong way, I wasn't asking for a real release on all operating systems. Just a zip file of code, you already have on your hard disk. I understand that doing a proper release takes time. I wasn't asking for that. And I do understand and appreciate what great work you are doing. 

I'd usually compile it myself, but I already have several different development environments on my machine.

Well, let's see - maybe I can install the pre-reqs and add another den env to my collection. :-)

**Comment by stennie** [comment]
@tessus This is a Qt project (not Xcode) so the step to make an app unfortunately isn't as simple as a zip & copy (the Qt libs are dynamically linked, for example). You're correct that all the changes should be committed for 0.8.5 (aside from any lingering build errors on Windows which still need to be investigated).

I have the tuits to get a 0.8.5 release out for OS X shortly. What I'd *really* like to get finished is the 0.9.0 release with updated shell and 3.0 support :-D.

**Comment by tessus** [comment]
@stennie just installed the pre-reqs (oh yeah - more dev libs and tools), but ran into the same compile issues as people in #743. I guess I will have to wait then. I tried.

**Comment by topilski** [comment]
Hello @tessus please specify your emai and i will send you last dmg of Robomongo.

**Comment by tessus** [comment]
@topilski Wow. That's awesome. How did you manage to overcome the issue in #743?

My mail server rejects all mails larger than 10MB. But I do have my own cloud storage and it would be great, if you could [upload](https://cloud.evermeet.cx/public.php?service=files&t=cec69bc95a9d9d4494a5276221e99f43) it there (no user required).

**Comment by gavruk** [comment]
@topilski, can you also help to fix building on Windows? :)

**Comment by topilski** [comment]
My build machine is 10.8, yup i tried to send to your but message was rejected.

**Comment by topilski** [comment]
@gavruk yes of course. What issue?

**Comment by tessus** [comment]
@topilski Sorry, my mail server rejects all mails larger than 10MB. 

But I do have my own cloud storage and it would be great, if you could [upload](https://cloud.evermeet.cx/public.php?service=files&t=cec69bc95a9d9d4494a5276221e99f43) it there (no user required).

**Comment by tessus** [comment]
@topilski works great. thank you.

**Comment by createproblem** [comment]
Works also great for me, thanks.

**Comment by rabc** [comment]
So, if I understood it right, Paralect just gave up the project, right?

Seeing the [contributors chart](https://github.com/paralect/robomongo/graphs/contributors), it's clear that @tessus is doing almost all the work since July/2014. Besides that, we just had a person from Paralect appeared from nothing just to compile.

That's why things like io.js happens. @tessus, go ahead and fork it, please.

**Comment by stennie** [comment]
@rabc Paralect added me as a contributor to the project so I'm able to merge fixes to master and manage the issue queue. They've been focused on other projects but still manage aspects like the Robomongo web site. I originally volunteered to help keep things moving (even if slowly) until they were able to contribute more dev resource. I'll follow up with them to find out if there is any update on their plans.

I don't think forking adds any benefit. The main impediment to progress at the moment is a lack of contributors (or spare time from the contributors who have volunteered so far).

**Comment by stennie** [comment]
Fixed a few build issues with releases and packaging 0.8.5 toda (will ask Paralect to update the robomongo.org site).

OS X 0.8.5: https://www.dropbox.com/s/8lawkd1ka7sgia9/Robomongo-0.8.5-x86_64.dmg?dl=0

If you test this out and find any problems, please start a new issue. Thanks!
