### ISSUE TITLE
Some keys not working in 0.8.5 (Windows remote to Ubuntu running xrdp)

### ISSUE THREAD

**Issue by Eisrep** [paralect/robomongo#804]
This is a follow-up from: [#716](https://github.com/paralect/robomongo/issues/716)

I am using a Windows machine to remote into Ubuntu running xfce4 through xrdp. The 0.8.5 preview fixed the main issue with the keyboard not working. But I now notice that the arrow keys do not work while typing. Up, Left, and Right do not seem to do anything. The Down arrow will act as a return--creating a new line where the cursor was.

This doesn't happen in the other programs I use (Sublime Text 2, Chrome, Terminal).

Edit: Other keys not working: Delete, End, Page Down, Page Up, Home, Insert.
(Insert will create a '/')

**Comment by stennie** [comment]
@Eisrep It sounds like your issue is likely related to xrdp + Qt. There are a number of keyboard-related issues if you dig through the QTBUG queue, eg: [QTBUG-39344](https://bugreports.qt.io/browse/QTBUG-39344), [QTBUG-34483](https://bugreports.qt.io/browse/QTBUG-34483), [QTBUG-32760](https://bugreports.qt.io/browse/QTBUG-32760).

For example, one comment on QTBUG-32760 sounds like your issue (although was closed as resolved for Qt 5.3.0 and the Robomongo 0.8.5 packages are using Qt 5.3.2): 
> We are using the default realvnc (no XKEYBOARD support) on Debian 7. With Qt5.3 and Qt5.4 , the normal keys are mostly working, but we found that the special keys, lock keys, direction keys and the numeric keypad are acting weird.

A few comments mention updating xkeyboard-config may fix. Given you have a rather atypical setup, it would be helpful if you could have a look through the QTBUG issue tracker as well and see if there are any suggestions that might be worth trying. I didn't spot anything relevant in the [xrdp GitHub issue queue](https://github.com/neutrinolabs/xrdp) but you could also try filing a bug report there with details of your environment.

What are your versions of Ubuntu and xrdp?

**Comment by Eisrep** [comment]
@stennie Thanks for looking into this for me. I am using Ubuntu 14.04.2 LTS and xrdp 0.6.0-1

 I do believe this is an issue between xrdp and Qt. I read [QTBUG-32760](https://bugreports.qt.io/browse/QTBUG-32760) and it sounds exactly like my problem.

Although I don't know where to go from there but that is beside point.

This is unlikely to be a bug with Robomongo.

**Comment by stennie** [comment]
@Eisrep Did you try any of the suggestions there? Also, are you seeing any errors logged that might help?

Looks like a few ideas you could try:

 - add `XKB_DEFAULT_RULES=base` to the `robomongo.sh` launch script

 - install `xkeyboard-config`

 > http://cgit.freedesktop.org/xkeyboard-config/ . You should build this library and install it in the path that was pointed to by xkb-config-root or use the QT_XKB_CONFIG_ROOT envvar to tell Qt where you have installed the xkb configs.

 - use VNC instead of xrdp

**Comment by Eisrep** [comment]
@stennie Oh. I had no idea where to put "XKB_DEFAULT_RULES=base". That actually solves the problem.

Thanks a lot! I really appreciate the help you've given me.

**Comment by stennie** [comment]
@Eisrep Great, thanks for confirming! I'll test the change and if it doesn't break anything in other Linux environments will commit it for the next package update.
