### ISSUE TITLE
Error with the new stats() functionality in MongoDB 3.0

### ISSUE THREAD

**Issue by Nicte** [paralect/robomongo#815]
Hi,

When I execute this in the mongo shell it works fine:

```javascript
db.people.stats({scale: 1024, indexDetails: true, indexKey: {order_date: 1}})
```

When I try it through Robomongo 0.8.5 it gives an error saying "scale has to be a number >= 1"

Just wanted to let you guys know. This method has been updated in 3.0:

http://docs.mongodb.org/manual/reference/method/db.collection.stats/#db.collection.stats
![img1](https://cloud.githubusercontent.com/assets/4835465/6769870/9dbd6ac2-d0ac-11e4-934f-0f0479c34f8a.png)

Great work by the way! Awesome tool!

Nicte

**Comment by stennie** [comment]
@Nicte Thanks for the feedback. Robomongo 0.8.x is using the older MongoDB 2.4.x shell so expects scale to be a parameter rather than an object. The older shell helper also doesn't do any of the result filtering (i.e. `indexDetails` parameters added in MongoDB 3.0). 

Supported syntax in Robomongo 0.8.x is to only pass through a scale option: `db.people.stats(1024)`.

FYI, working on updating to the 3.0 shell for the [Robomongo 0.9.0 milestone](https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0).

**Comment by schetnikovich** [comment]
@Nicte Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
