### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by schetnikovich** [paralect/robomongo#827]
Couple of days ago I received email from Gabriel Bernal, who proposed new logo:

![](http://robomongo.org/files/new-robomongo-logo.png)

In my opinion, this logo visually connected with MongoDB a bit better, than our current. If most of us will find this appealing, then it makes sense to use this logo in our next releases.

Gabriel kindly provided us with PSD source and couple of resolution variants:
http://robomongo.org/files/new-robomongo-logo.zip

Thank you, Gabriel!

**Comment by stennie** [comment]
Given we've only just changed the logo from a generic one for the 0.8.5 release, I think it would be much better to focus on other needed cosmetic improvements like better toolbar icons (#725). At some future point we could have an open logo competition but at this stage it's just [bikeshedding](http://bikeshed.com/) imho.

A more vertical logo like this suggestion is harder to fit into the more typically square space available for application icons.

I also think we should also be wary of looking too similar to the one-eyed [MMS Automation Agent](https://dribbble.com/shots/1601108-MMS-Automation-Agent) or the green [MongoDB Leafie character](https://dribbble.com/emilymatsuno) being used by MongoDB, Inc.

**Comment by thinklinux** [comment]
+1 for a new logo :) 

The generic one was better than the 0.8.5 logo imho. This one is really cool and I don't see anything bad in using the green leaf as a connection to the MongoDB. RoboLeaf => RoboMongo. Not bad at all.

The only problem is really the vertical design.

I think a good logo icon is a vital part of any application software now so don't underestimate that.

**Comment by stennie** [comment]
@thinklinux I'm not underestimating the value of a nice logo (which is why I'm happy the generic one was replaced with a community contribution for Robomongo 0.8.5). However, I don't think it merits extended discussion at this point given there are more important code changes to address first. If anyone prefers to use a different logo in their own environment this is an easy change to make; you should be able to install the normal application and override the icon in your O/S preferences.

I'd like to park this discussion as a distraction for the moment so we can focus on more fundamental issues. There was some thought put into the current logo, and if we want to choose a new logo we can create an updated brief and open it up to a competition or community vote of some sort. It's hard to get consensus on designs that Everyone likes .. however, the features that currently have the most support in the [backlog](http://robomongo.org/backlog) are all about functionality rather than cosmetics.

**Comment by ApfelUser** [comment]
:+1: for Gabriel Bernal's new Logo, looks great in my opinion and I don't understand why it shouldn't be taken.

**Comment by lucaskatayama** [comment]
Nice +1

**Comment by stennie** [comment]
To summarise my earlier comments on the issue:
 - the logo was just changed from generic to a contributed design in the previous release (0.8.5)
 - it's a trivial change to make on your local system if you'd prefer something different
 - this isn't a priority to change at the moment (but there are other cosmetic issues like toolbar icons that could definitely use help)
 - we can open up to a proper competition or community vote with a design brief in future, as there are bound to be differing preferences

**Comment by schetnikovich** [comment]
Starting from Robomongo 0.9.0, new icon is used.
