### ISSUE TITLE
wrong presentation of NumberInt at the TextView

### ISSUE THREAD

**Issue by yonicc** [paralect/robomongo#853]
every number shown as 
![image](https://cloud.githubusercontent.com/assets/3640988/7248440/4fe935c0-e81b-11e4-848a-82246b349b42.png)
 instead of readable number

**Comment by millisecond** [comment]
Was just coming here to report this as well.  When editing the document it shows this e-notation and then saving it back tries to convert it back to a long and fails to achieve the same precision messing up documents.  We've even had the _id field be this and start saving dupes / overwriting other docs.  

Very dangerous.

**Comment by stennie** [comment]
@yonicc, @millisecond This is a bug in Robomongo 0.8.5 which should be fixed in Robomongo 0.8.6 (see #831). Will be posting some test packages this weekend with links on the relevant issues in the [0.8.6 milestone](https://github.com/paralect/robomongo/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A%22Robomongo+0.8.6%22+label%3Atask+create). Would appreciate any help testing the release candidates :).

If you want a workaround in the interim you could either [downgrade to Robomongo 0.8.4](http://robomongo.org/download.html) as a workaround or build from current master.
