### ISSUE TITLE
Large number crashes Robomongo [linux]

### ISSUE THREAD

**Issue by ghost** [paralect/robomongo#892]
I inserted a vary large number with "insert document" and it crashed Robomongo.

Example:

```javascript
{
   num: 999999999999999999999999999999999999999999999
}
```

**Comment by schetnikovich** [comment]
@ghost This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.

Document that you mentioned will be of type `Double`, because it doesn't fit in `NumberInt` or `NumberLong`. And it will be represented in such notation: `9.999999999999999e+044`
