### ISSUE TITLE
once ssh, leaves open connections, lots of them.

### ISSUE THREAD

**Issue by dotpot** [paralect/robomongo#898]
I've configured connection to db over ssh.

issues:
- each query opens up new ssh connection.
- disconecting from db does not close them.
- closing whole application closes all connections.

**Comment by anorsich** [comment]
@dotpot 

This issue has been fixed in 0.9.0 RC8, SSH connections were reworked from scratch and now does not leak open connections and in general works faster. You can read more about the release in our [blog post](http://blog.robomongo.org/robomongo-rc8/).

Thank you for issue report and sorry for the late reply. From now and moving we will be fixing bugs faster :)
