### ISSUE TITLE
does robomongo support mongodb v3.0.5 

### ISSUE THREAD

**Issue by bboalimoe** [paralect/robomongo#932]
thanks

**Comment by sleske** [comment]
No, it does not. See #520 for details.

**Comment by sleske** [comment]
I think this can be closed as a dupe of #520, but I don't have sufficient rights on GitHub. Maybe someone else can do this...

**Comment by RumenTech** [comment]
Hi,

When is the v0.9.0 being released?
I use mongodb running inside vagrant, and can load database but no collections.
(Similar to https://github.com/paralect/robomongo/issues/435)
And I found the reason here - https://github.com/paralect/robomongo/issues/520.
I really love robomongo and I'm eager to use the new version. (Other products allow me to see collections with same connection)

Thank you.

**Comment by schetnikovich** [comment]
@bboalimoe @sleske @RumenTech Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.

**Comment by RumenTech** [comment]
@schetnikovich 
It's really a great news! Thanks for your hard work.

**Comment by bboalimoe** [comment]
@schetnikovich  Thanks you!
