### ISSUE TITLE
Application quits unexpectedly when unplugging external monitor

### ISSUE THREAD

**Issue by yonatanzelnik** [paralect/robomongo#936]

**Comment by simison** [comment]
Duplicate of #829 

@yonatanzelnik Could you check your OSX version? I had the same issue but it disappeared after upgrading to OSX 10.10.5.

**Comment by yonatanzelnik** [comment]
Got it. OSX is 10.10.3.

**Comment by anorsich** [comment]
@yonatanzelnik I hope that this issue has been fixed with latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) release. Also I going to close this ticket as duplicate of #829, please use this ticket if it still does not work fo you or if you'll have any finding that will help us replicate the issue.
