### ISSUE TITLE
Reorder permanently by key

### ISSUE THREAD

**Issue by welovedesign** [paralect/robomongo#941]
This is my schema how do I permanently reorder them , the items seems to have a key

http://pasteboard.co/xiy4u4W.png

no 1. actually itemIndex 22 - I want itemIndex to be the Index.

{
    "_id" : "MovZQzjfGqBbcQd2c",
    "item" : "my item 1",
    "permalink" : "no-knives",
    "itemIndex" : 22,
    "shortDescription" : "A description goes here",

}

**Comment by anorsich** [comment]
@welovedesign Thank for sumitting the issue. The _id field is shown in a tree view by design. I don't think we can change it, because most of the people want to see _id. I think in your case you can just switch over to the table view to see itemIndex field, or in case if itemIndex is unique you might want to use it as _id for your document.
