### ISSUE TITLE
Auth support mongodb 3.0+

### ISSUE THREAD

**Issue by ramkumar-g** [paralect/robomongo#973]
Hi

When can we expect the next version which launches auth support for mongodb 3.0+

**Comment by PavelPolyakov** [comment]
+1

**Comment by MarkoCen** [comment]
Seem like they are stop working on this project. The last commit almost 7 months ago :\

**Comment by ChristianSyn** [comment]
To solve the V3.0x problem I have decided to use MongoChef : http://3t.io/mongochef/

**Comment by PavelPolyakov** [comment]
I don't find MongoChef so convenient as RoboMongo.

@schetnikovich @stennie 
Maybe you can launch a found raising campaign in order to gather some money to speed up the Mongo v3 development? I think community would able to donate some money.

In the best scenario, the goal number should be defined - if we gather it, RoboMongo for mongo3, would be developed, then.

@community
Please, support, if you like the idea.

**Comment by smmorneau** [comment]
Looks like this should be ready by January 17. http://blog.robomongo.org/support-for-mongodb-3x-in-20-days/

**Comment by schetnikovich** [comment]
@ramkumar-g Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
